"""add_flight_date_to_orders

Revision ID: 07934df93c1c
Revises: f82e11fede1e
Create Date: 2026-06-08 12:09:55.773592

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07934df93c1c'
down_revision: str | None = 'f82e11fede1e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('flight_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'flight_date')
    # ### end Alembic commands ###
