"""add_all_tables

Revision ID: 5382bb69f1ea
Revises: 0001_initial
Create Date: 2026-05-21 05:07:34.127502
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5382bb69f1ea'
down_revision: str | None = '0001_initial'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('depart_iata', sa.String(length=3), nullable=False),
    sa.Column('arrive_iata', sa.String(length=3), nullable=False),
    sa.Column('airline', sa.String(length=64), nullable=True),
    sa.Column('allowed_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('allowed_kg > 0', name=op.f('ck_routes_kg_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes')),
    sa.UniqueConstraint('depart_iata', 'arrive_iata', 'airline', name='uq_route_iata_airline')
    )
    op.create_table('sourcing_specs',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('default_weight_g', sa.Integer(), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_urgent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_customer_orderable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('value_tier', postgresql.ENUM('regular', 'luxury', name='value_tier_enum', create_type=False), server_default='regular', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sourcing_specs'))
    )
    op.create_index('ix_sourcing_specs_category', 'sourcing_specs', ['category'], unique=False)
    op.create_index('ix_sourcing_specs_is_urgent', 'sourcing_specs', ['is_urgent'], unique=False)
    op.create_index('ix_sourcing_specs_title_trgm', 'sourcing_specs', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_table('audit_log',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_table', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_log_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_action_at', 'audit_log', ['action', 'at'], unique=False)
    op.create_index('ix_audit_log_actor_at', 'audit_log', ['actor_user_id', 'at'], unique=False)
    op.create_index('ix_audit_log_target', 'audit_log', ['target_table', 'target_id'], unique=False)
    op.create_table('carrier_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('passport_number', sa.String(length=32), nullable=False),
    sa.Column('passport_country', sa.String(length=3), nullable=False),
    sa.Column('passport_expires_on', sa.Date(), nullable=False),
    sa.Column('passport_photo_url', sa.Text(), nullable=True),
    sa.Column('selfie_photo_url', sa.Text(), nullable=True),
    sa.Column('ticket_photo_url', sa.Text(), nullable=True),
    sa.Column('flight_number', sa.String(length=16), nullable=True),
    sa.Column('depart_airport_iata', sa.String(length=3), nullable=False),
    sa.Column('arrive_airport_iata', sa.String(length=3), nullable=False),
    sa.Column('depart_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrive_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('allowed_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('trust_tier', postgresql.ENUM('new', 'standard', 'trusted', 'vip', name='trust_enum', create_type=False), server_default='new', nullable=False),
    sa.Column('liability_consented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_trip_value_cap', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('onboarding_channel', postgresql.ENUM('self_serve', 'airport_backside', 'admin_invited', name='onboarding_enum', create_type=False), nullable=False),
    sa.Column('selfie_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blacklisted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('landing_reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('allowed_kg > 0', name=op.f('ck_carrier_profiles_allowed_kg_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_carrier_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_carrier_profiles'))
    )
    op.create_index('ix_carrier_profiles_arrive_at', 'carrier_profiles', ['arrive_at'], unique=False)
    op.create_index('ix_carrier_profiles_trust_tier', 'carrier_profiles', ['trust_tier'], unique=False)
    op.create_table('walk_in_customers',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('id_document_last4', sa.String(length=4), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(phone) >= 7', name=op.f('ck_walk_in_customers_phone_min_length')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_walk_in_customers_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_walk_in_customers'))
    )
    op.create_index('ix_walk_in_customers_phone', 'walk_in_customers', ['phone'], unique=False)
    op.create_table('orders',
    sa.Column('orderer_user_id', sa.UUID(), nullable=True),
    sa.Column('walk_in_customer_id', sa.UUID(), nullable=True),
    sa.Column('source', postgresql.ENUM('self_via_bot', 'on_behalf_walkin', name='order_source_enum', create_type=False), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('draft', 'pending_sourcing', 'sourcing', 'in_transit_cn_uz', 'at_tashkent', 'in_transit_uz_tr', 'at_tr_wh', 'partially_delivered', 'delivered', 'cancelled', 'disputed', name='order_status_enum', create_type=False), server_default='draft', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(orderer_user_id IS NOT NULL) <> (walk_in_customer_id IS NOT NULL)', name=op.f('ck_orders_orderer_xor_walkin')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_orders_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['orderer_user_id'], ['users.id'], name=op.f('fk_orders_orderer_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['walk_in_customer_id'], ['walk_in_customers.id'], name=op.f('fk_orders_walk_in_customer_id_walk_in_customers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_orderer_user_id', 'orders', ['orderer_user_id'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_walk_in_customer_id', 'orders', ['walk_in_customer_id'], unique=False)
    op.create_table('payouts',
    sa.Column('carrier_user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', postgresql.ENUM('cash', 'bank', 'crypto', 'other', name='payout_method_enum', create_type=False), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('fx_base_currency', sa.String(length=3), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('requested', 'approved', 'paid', 'rejected', name='payout_status_enum', create_type=False), server_default='requested', nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_payouts_amount_non_negative')),
    sa.ForeignKeyConstraint(['carrier_user_id'], ['carrier_profiles.user_id'], name=op.f('fk_payouts_carrier_user_id_carrier_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paid_by_admin_id'], ['users.id'], name=op.f('fk_payouts_paid_by_admin_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payouts'))
    )
    op.create_index('ix_payouts_carrier_status', 'payouts', ['carrier_user_id', 'status'], unique=False)
    op.create_index('ix_payouts_requested_at', 'payouts', ['requested_at'], unique=False)
    op.create_table('order_lines',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('sourcing_spec_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('target_unit_weight_g', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('customer_paid_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('customer_paid_currency', sa.String(length=3), nullable=True),
    sa.Column('count_received', sa.Integer(), nullable=True),
    sa.Column('fulfillment_status', postgresql.ENUM('pending_sourcing', 'sourcing', 'in_transit', 'received_full', 'received_partial', 'received_over', 'cancelled', name='fulfillment_enum', create_type=False), server_default='pending_sourcing', nullable=False),
    sa.Column('has_quality_issue', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('count_received IS NULL OR count_received >= 0', name=op.f('ck_order_lines_count_received_non_negative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_lines_quantity_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_lines_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sourcing_spec_id'], ['sourcing_specs.id'], name=op.f('fk_order_lines_sourcing_spec_id_sourcing_specs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_lines'))
    )
    op.create_index('ix_order_lines_fulfillment_status', 'order_lines', ['fulfillment_status'], unique=False)
    op.create_index('ix_order_lines_order_id', 'order_lines', ['order_id'], unique=False)
    op.create_index('ix_order_lines_sourcing_spec_id', 'order_lines', ['sourcing_spec_id'], unique=False)
    op.create_table('products',
    sa.Column('short_code', sa.String(length=8), nullable=False),
    sa.Column('order_line_id', sa.UUID(), nullable=True),
    sa.Column('sourcing_spec_id', sa.UUID(), nullable=False),
    sa.Column('unit_weight_g', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('intake_photo_url', sa.Text(), nullable=True),
    sa.Column('cargo_price_uz_to_tr', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cargo_currency', sa.String(length=3), server_default='UZS', nullable=False),
    sa.Column('condition_on_intake', postgresql.ENUM('ok', 'damaged', 'wrong_spec', name='condition_enum', create_type=False), server_default='ok', nullable=False),
    sa.Column('status', postgresql.ENUM('pending_intake', 'at_tashkent_wh', 'in_basket', 'with_courier_uz', 'with_carrier', 'in_flight', 'with_courier_tr', 'at_tr_wh', 'delivered', 'lost', 'cancelled', name='product_status_enum', create_type=False), nullable=False),
    sa.Column('custody_holder_type', postgresql.ENUM('china_supplier', 'in_transit_cn_uz', 'tashkent_wh', 'courier_uz', 'yandex_bridge', 'carrier', 'courier_tr', 'tr_wh', 'orderer', 'orderer_walkin', 'lost', name='holder_type_enum', create_type=False), nullable=False),
    sa.Column('custody_holder_id', sa.UUID(), nullable=True),
    sa.Column('qr_payload', sa.Text(), nullable=False),
    sa.Column('barcode_payload', sa.String(length=64), nullable=False),
    sa.Column('label_printed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('label_attached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('flagged_lost', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('cargo_price_uz_to_tr >= 0', name=op.f('ck_products_price_non_negative')),
    sa.CheckConstraint('unit_weight_g > 0', name=op.f('ck_products_weight_positive')),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], name=op.f('fk_products_order_line_id_order_lines'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sourcing_spec_id'], ['sourcing_specs.id'], name=op.f('fk_products_sourcing_spec_id_sourcing_specs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('short_code', name=op.f('uq_products_short_code'))
    )
    op.create_index('ix_products_at_tashkent_by_spec', 'products', ['sourcing_spec_id', 'status'], unique=False, postgresql_where="status = 'at_tashkent_wh'")
    op.create_index('ix_products_created_at', 'products', ['created_at'], unique=False)
    op.create_index('ix_products_order_line_id', 'products', ['order_line_id'], unique=False)
    op.create_index('ix_products_short_code', 'products', ['short_code'], unique=True)
    op.create_index('ix_products_status_holder', 'products', ['status', 'custody_holder_type', 'custody_holder_id'], unique=False)
    op.create_table('carrier_picks',
    sa.Column('carrier_user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('locked_cargo_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('locked_currency', sa.String(length=3), nullable=False),
    sa.Column('handoff_mode', postgresql.ENUM('wh_pickup', 'free_tashkent', 'yandex', 'airport_backside', name='handoff_mode_enum', create_type=False), nullable=True),
    sa.Column('handoff_status', postgresql.ENUM('in_basket', 'awaiting_handoff', 'carrier_has_custody', 'in_flight', 'landed', 'dropped_off', 'delivered', 'cancelled', name='handoff_status_enum', create_type=False), nullable=False),
    sa.Column('delivery_address_uz', sa.Text(), nullable=True),
    sa.Column('delivery_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('yandex_order_id', sa.String(length=64), nullable=True),
    sa.Column('tr_delivery_mode', postgresql.ENUM('tr_courier_from_carrier', 'carrier_dropoff', name='tr_delivery_enum', create_type=False), nullable=True),
    sa.Column('carrier_address_tr', sa.Text(), nullable=True),
    sa.Column('picked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('basket_lock_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payout_eligible_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispute_status', postgresql.ENUM('none', 'disputed', 'resolved', name='dispute_enum', create_type=False), server_default='none', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('locked_cargo_price >= 0', name=op.f('ck_carrier_picks_locked_price_non_negative')),
    sa.ForeignKeyConstraint(['carrier_user_id'], ['carrier_profiles.user_id'], name=op.f('fk_carrier_picks_carrier_user_id_carrier_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_carrier_picks_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carrier_picks')),
    sa.UniqueConstraint('product_id', name='uq_one_carrier_per_product'),
    sa.UniqueConstraint('product_id', name=op.f('uq_carrier_picks_product_id'))
    )
    op.create_index('ix_carrier_picks_basket_lock', 'carrier_picks', ['basket_lock_until'], unique=False)
    op.create_index('ix_carrier_picks_carrier_status', 'carrier_picks', ['carrier_user_id', 'handoff_status'], unique=False)
    op.create_index('ix_carrier_picks_payout_eligible_at', 'carrier_picks', ['payout_eligible_at'], unique=False)
    op.create_table('custody_events',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('event_type', postgresql.ENUM('created', 'picked_by_courier', 'delivered_to_carrier', 'yandex_sealed', 'yandex_received', 'departed', 'landed', 'handed_to_tr_courier', 'handed_to_tr_wh', 'delivered_to_orderer', 'flagged_lost', 'returned', 'admin_override', name='event_type_enum', create_type=False), nullable=False),
    sa.Column('from_holder_type', postgresql.ENUM('china_supplier', 'in_transit_cn_uz', 'tashkent_wh', 'courier_uz', 'yandex_bridge', 'carrier', 'courier_tr', 'tr_wh', 'orderer', 'orderer_walkin', 'lost', name='holder_type_enum', create_type=False), nullable=True),
    sa.Column('from_holder_id', sa.UUID(), nullable=True),
    sa.Column('to_holder_type', postgresql.ENUM('china_supplier', 'in_transit_cn_uz', 'tashkent_wh', 'courier_uz', 'yandex_bridge', 'carrier', 'courier_tr', 'tr_wh', 'orderer', 'orderer_walkin', 'lost', name='holder_type_enum', create_type=False), nullable=False),
    sa.Column('to_holder_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('seal_number', sa.String(length=64), nullable=True),
    sa.Column('handoff_code', sa.String(length=16), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('geo_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('geo_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_custody_events_actor_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_custody_events_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custody_events'))
    )
    op.create_index('ix_custody_events_actor_at', 'custody_events', ['actor_user_id', 'at'], unique=False)
    op.create_index('ix_custody_events_event_type', 'custody_events', ['event_type'], unique=False)
    op.create_index('ix_custody_events_product_at', 'custody_events', ['product_id', 'at'], unique=False)
    op.create_index('ix_custody_events_session_id', 'custody_events', ['session_id'], unique=False)
    op.create_table('disputes',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('lost', 'damaged', 'wrong_item', 'not_received', name='dispute_type_enum', create_type=False), nullable=False),
    sa.Column('raised_by_user_id', sa.UUID(), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('evidence_urls', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('custody_event_id_at_dispute', sa.UUID(), nullable=True),
    sa.Column('resolution', postgresql.ENUM('deduct', 'write_off', 'reorder', 'refund_orderer', name='dispute_resolution_enum', create_type=False), nullable=True),
    sa.Column('resolved_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['custody_event_id_at_dispute'], ['custody_events.id'], name=op.f('fk_disputes_custody_event_id_at_dispute_custody_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_disputes_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raised_by_user_id'], ['users.id'], name=op.f('fk_disputes_raised_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by_admin_id'], ['users.id'], name=op.f('fk_disputes_resolved_by_admin_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disputes'))
    )
    op.create_index('ix_disputes_product_id', 'disputes', ['product_id'], unique=False)
    op.create_index('ix_disputes_raised_at', 'disputes', ['raised_at'], unique=False)
    op.create_index('ix_disputes_unresolved', 'disputes', ['raised_at'], unique=False, postgresql_where='resolved_at IS NULL')
    op.create_table('payout_lines',
    sa.Column('payout_id', sa.UUID(), nullable=False),
    sa.Column('carrier_pick_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('deduction', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('deduction_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_payout_lines_line_amount_non_negative')),
    sa.CheckConstraint('deduction >= 0', name=op.f('ck_payout_lines_deduction_non_negative')),
    sa.ForeignKeyConstraint(['carrier_pick_id'], ['carrier_picks.id'], name=op.f('fk_payout_lines_carrier_pick_id_carrier_picks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], name=op.f('fk_payout_lines_payout_id_payouts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payout_lines'))
    )
    op.create_index('ix_payout_lines_carrier_pick_id', 'payout_lines', ['carrier_pick_id'], unique=False)
    op.create_index('ix_payout_lines_payout_id', 'payout_lines', ['payout_id'], unique=False)
    op.create_unique_constraint('uq_user_role', 'user_roles', ['user_id', 'role'])
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    op.drop_index('ix_payout_lines_payout_id', table_name='payout_lines')
    op.drop_index('ix_payout_lines_carrier_pick_id', table_name='payout_lines')
    op.drop_table('payout_lines')
    op.drop_index('ix_disputes_unresolved', table_name='disputes', postgresql_where='resolved_at IS NULL')
    op.drop_index('ix_disputes_raised_at', table_name='disputes')
    op.drop_index('ix_disputes_product_id', table_name='disputes')
    op.drop_table('disputes')
    op.drop_index('ix_custody_events_session_id', table_name='custody_events')
    op.drop_index('ix_custody_events_product_at', table_name='custody_events')
    op.drop_index('ix_custody_events_event_type', table_name='custody_events')
    op.drop_index('ix_custody_events_actor_at', table_name='custody_events')
    op.drop_table('custody_events')
    op.drop_index('ix_carrier_picks_payout_eligible_at', table_name='carrier_picks')
    op.drop_index('ix_carrier_picks_carrier_status', table_name='carrier_picks')
    op.drop_index('ix_carrier_picks_basket_lock', table_name='carrier_picks')
    op.drop_table('carrier_picks')
    op.drop_index('ix_products_status_holder', table_name='products')
    op.drop_index('ix_products_short_code', table_name='products')
    op.drop_index('ix_products_order_line_id', table_name='products')
    op.drop_index('ix_products_created_at', table_name='products')
    op.drop_index('ix_products_at_tashkent_by_spec', table_name='products', postgresql_where="status = 'at_tashkent_wh'")
    op.drop_table('products')
    op.drop_index('ix_order_lines_sourcing_spec_id', table_name='order_lines')
    op.drop_index('ix_order_lines_order_id', table_name='order_lines')
    op.drop_index('ix_order_lines_fulfillment_status', table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_index('ix_payouts_requested_at', table_name='payouts')
    op.drop_index('ix_payouts_carrier_status', table_name='payouts')
    op.drop_table('payouts')
    op.drop_index('ix_orders_walk_in_customer_id', table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_orderer_user_id', table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_walk_in_customers_phone', table_name='walk_in_customers')
    op.drop_table('walk_in_customers')
    op.drop_index('ix_carrier_profiles_trust_tier', table_name='carrier_profiles')
    op.drop_index('ix_carrier_profiles_arrive_at', table_name='carrier_profiles')
    op.drop_table('carrier_profiles')
    op.drop_index('ix_audit_log_target', table_name='audit_log')
    op.drop_index('ix_audit_log_actor_at', table_name='audit_log')
    op.drop_index('ix_audit_log_action_at', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_sourcing_specs_title_trgm', table_name='sourcing_specs', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_sourcing_specs_is_urgent', table_name='sourcing_specs')
    op.drop_index('ix_sourcing_specs_category', table_name='sourcing_specs')
    op.drop_table('sourcing_specs')
    op.drop_table('routes')
    # ### end Alembic commands ###
