"""add_with_courier_uz_status

Revision ID: f82e11fede1e
Revises: 0003
Create Date: 2026-06-08 11:57:13.841071

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82e11fede1e'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_barcode_key', 'products', type_='unique')
    op.drop_index('ix_products_barcode', table_name='products')
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.drop_constraint('users_telegram_id_key', 'users', type_='unique')
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=False)
    op.create_unique_constraint('users_telegram_id_key', 'users', ['telegram_id'])
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.create_index('ix_products_barcode', 'products', ['barcode'], unique=False)
    op.create_unique_constraint('products_barcode_key', 'products', ['barcode'])
    # ### end Alembic commands ###
